VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ClsOriginInfoDto"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

    Public RowCnt As Integer
    Public ColCnt As Integer
    Public StartRowPos As Integer
    Public StartColumnPos As Integer
    Public Max_RowPos As Integer
    Public Max_ColumnPos As Integer
    Public Prm_Value_ColPos As Integer
    Public Case_Value_ColPos As Integer
    Public Prm_Name_ColPos As Integer
